baseURL: # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: My Portfolio
paginate: 5
theme: papermod
math: true



menu:
    main:
        - name: Contact
          url: contact/
          weight: 30
        - name: Articles
          url: articles/
          weight: 20
        - name: Projects
          url: projects
          weight: 15

     # - name: Categories
        #   url: categories/
        #   weight: 10
        # - name: new Tab
        #   url: mewtab/
        #   weight: defines order of tabs
   


params:
    author: Noé Vernier


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    math: true

    profileMode:
        enabled: true
        title: Noé Vernier
        description: |
          Hello, I am Noé.
           I study Computer Science at TelecomParis. 
        
          This is my portfolio.
        imageUrl: "/images/profile.jpg"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Contact me
              url: https://www.linkedin.com/in/noe-vernier
    mainSections:
      - articles

    socialIcons:
        - name: twitter
          url: "https://twitter.com/NoeVernier"
        - name: github
          url: "https://github.com/noevernier"
        - name: linkedin
          url: "https://www.linkedin.com/in/noe-vernier"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

